"""initial lims schema

Revision ID: 0001
Revises:
Create Date: 2026-10-04 11:07:07.167296

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counter",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_counter_updated_at"), "counter", ["updated_at"], unique=False)
    op.create_table(
        "sample",
        sa.Column("sample_id", sa.Text(), nullable=False),
        sa.Column("inspection_lot_no", sa.Text(), nullable=False),
        sa.Column("material_no", sa.Text(), nullable=False),
        sa.Column("batch_no", sa.Text(), nullable=False),
        sa.Column("collected_date", sa.Date(), nullable=False),
        sa.Column("offsite_test", sa.Boolean(), nullable=False),
        sa.Column("external_lab", sa.Text(), nullable=True),
        sa.Column("shipped_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status in ('registered', 'in_progress', 'approved', 'rejected')", name="ck_sample_status"
        ),
        sa.PrimaryKeyConstraint("sample_id"),
    )
    op.create_index("ix_sample_lot", "sample", ["inspection_lot_no"], unique=False)
    op.create_index("ix_sample_material_batch", "sample", ["material_no", "batch_no"], unique=False)
    op.create_index(op.f("ix_sample_updated_at"), "sample", ["updated_at"], unique=False)
    op.create_table(
        "test_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sample_id", sa.Text(), nullable=False),
        sa.Column("test_code", sa.Text(), nullable=False),
        sa.Column("test_name", sa.Text(), nullable=False),
        sa.Column("result_value", sa.Text(), nullable=False),
        sa.Column("spec", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status in ('pending', 'pass', 'fail', 'oos')", name="ck_test_result_status"),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["sample.sample_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_test_result_sample", "test_result", ["sample_id"], unique=False)
    op.create_index(op.f("ix_test_result_updated_at"), "test_result", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_result_updated_at"), table_name="test_result")
    op.drop_index("ix_test_result_sample", table_name="test_result")
    op.drop_table("test_result")
    op.drop_index(op.f("ix_sample_updated_at"), table_name="sample")
    op.drop_index("ix_sample_material_batch", table_name="sample")
    op.drop_index("ix_sample_lot", table_name="sample")
    op.drop_table("sample")
    op.drop_index(op.f("ix_counter_updated_at"), table_name="counter")
    op.drop_table("counter")
    # ### end Alembic commands ###
