"""initial qms schema

Revision ID: 0001
Revises:
Create Date: 2026-10-04 11:09:00.658275

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counter",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_counter_updated_at"), "counter", ["updated_at"], unique=False)
    op.create_table(
        "deviation",
        sa.Column("deviation_no", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("opened_on", sa.Date(), nullable=False),
        sa.Column("closed_on", sa.Date(), nullable=True),
        sa.Column("root_cause_category", sa.Text(), nullable=False),
        sa.Column("owner", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("severity in ('minor', 'major', 'critical')", name="ck_deviation_severity"),
        sa.CheckConstraint("status in ('open', 'closed')", name="ck_deviation_status"),
        sa.PrimaryKeyConstraint("deviation_no"),
    )
    op.create_index(op.f("ix_deviation_updated_at"), "deviation", ["updated_at"], unique=False)
    op.create_table(
        "deviation_link",
        sa.Column("deviation_no", sa.Text(), nullable=False),
        sa.Column("material_no", sa.Text(), nullable=False),
        sa.Column("batch_no", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["deviation_no"],
            ["deviation.deviation_no"],
        ),
        sa.PrimaryKeyConstraint("deviation_no", "material_no", "batch_no"),
    )
    op.create_index(
        "ix_deviation_link_material_batch", "deviation_link", ["material_no", "batch_no"], unique=False
    )
    op.create_index(op.f("ix_deviation_link_updated_at"), "deviation_link", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deviation_link_updated_at"), table_name="deviation_link")
    op.drop_index("ix_deviation_link_material_batch", table_name="deviation_link")
    op.drop_table("deviation_link")
    op.drop_index(op.f("ix_deviation_updated_at"), table_name="deviation")
    op.drop_table("deviation")
    op.drop_index(op.f("ix_counter_updated_at"), table_name="counter")
    op.drop_table("counter")
    # ### end Alembic commands ###
