/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo Clock
         * @description The scenario service's clock; if it is down, the same clock read from the app database.
         */
        get: operations["demo_clock_api_clock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain Figure */
        get: operations["explain_figure_api_explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_api_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reference */
        get: operations["reference_api_reference_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rows/{row_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Row */
        get: operations["get_row_api_rows__row_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rows/{row_key}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Comment */
        post: operations["post_comment_api_rows__row_key__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rows/{row_key}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain Row */
        get: operations["explain_row_api_rows__row_key__explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rows/{row_key}/need-by": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Need By */
        put: operations["put_need_by_api_rows__row_key__need_by_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rows/{row_key}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Status */
        put: operations["put_status_api_rows__row_key__status_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_api_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger
         * @description Queue a manual sync (the worker mirrors whatever is published now).
         */
        post: operations["trigger_api_sync_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook */
        post: operations["webhook_api_sync_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Users
         * @description The personas for the switcher. It needs no identity (the switcher runs before one is chosen).
         */
        get: operations["users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertOut */
        AlertOut: {
            /** Count */
            count: number;
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: number;
            };
            /**
             * Kind
             * @enum {string}
             */
            kind: "air_gap" | "late" | "on_hold" | "rejected";
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["RowOut"][];
        };
        /** AuditOut */
        AuditOut: {
            /** Action */
            action: string;
            /** Actor User Key */
            actor_user_key: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Details */
            details: unknown;
            /** Id */
            id: number;
            /** Row Key */
            row_key: string | null;
        };
        /** AuditPage */
        AuditPage: {
            /** Items */
            items: components["schemas"]["AuditOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ClockOut */
        ClockOut: {
            /** Frozen */
            frozen: boolean;
            /**
             * Now Utc
             * Format: date-time
             */
            now_utc: string;
            /**
             * Today Local
             * Format: date
             */
            today_local: string;
        };
        /** CommentIn */
        CommentIn: {
            /** Body */
            body: string;
        };
        /** CommentOut */
        CommentOut: {
            /** Author User Key */
            author_user_key: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Row Key */
            row_key: string;
        };
        /** CompletionExplain */
        CompletionExplain: {
            /** Adjusted Reason Code */
            adjusted_reason_code: string | null;
            /** Applicable Slas */
            applicable_slas: unknown;
            /** Available Days */
            available_days: number | null;
            /** Base Slas */
            base_slas: {
                [key: string]: number;
            };
            /** Budget Days */
            budget_days: number | null;
            /** Compressed */
            compressed: boolean;
            /** Compression Ratio */
            compression_ratio: string | null;
            /** Days Remaining */
            days_remaining: number | null;
            /** Effective Slas */
            effective_slas: {
                [key: string]: number;
            };
            /** Entry Date */
            entry_date: string | null;
            /** Expected Completion */
            expected_completion: string | null;
            /** Formula */
            formula: string;
            freshness: components["schemas"]["Freshness"];
            /**
             * Kind
             * @default expected_completion
             * @constant
             */
            kind: "expected_completion";
            /** Must Complete By */
            must_complete_by: {
                [key: string]: string;
            };
            /** Need By Adjusted */
            need_by_adjusted: boolean;
            /** Operative Need By */
            operative_need_by: string | null;
            /** Rag */
            rag: string | null;
            /** Row Key */
            row_key: string;
            /** Stage Key */
            stage_key: string;
            /** System Need By */
            system_need_by: string | null;
        };
        /** DeviationOut */
        DeviationOut: {
            /** Closed On */
            closed_on: string | null;
            /** Deviation No */
            deviation_no: string;
            /** Opened On */
            opened_on: string | null;
            /** Owner */
            owner: string | null;
            /** Root Cause Category */
            root_cause_category: string | null;
            /** Severity */
            severity: string | null;
            /** Status */
            status: string | null;
            /** Title */
            title: string | null;
        };
        /** FlagsOut */
        FlagsOut: {
            /** Air Gap */
            air_gap: boolean;
            /** Erp Blocked */
            erp_blocked: boolean;
            /** Expedite */
            expedite: boolean;
            /** Full Spec */
            full_spec: boolean;
            /** Late */
            late: boolean;
            /** Lims Rejected */
            lims_rejected: boolean;
            /** Offsite */
            offsite: boolean;
            /** On Hold */
            on_hold: boolean;
            /** Re Eval */
            re_eval: boolean;
            /** Ud Rejected */
            ud_rejected: boolean;
        };
        /** FlowEntry */
        FlowEntry: {
            /** Breached */
            breached: boolean;
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Stage Key */
            stage_key: string;
        };
        /** FlowExplain */
        FlowExplain: {
            /** Breached */
            breached: boolean;
            /** Count */
            count: number;
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            freshness: components["schemas"]["Freshness"];
            /**
             * Kind
             * @default flow
             * @constant
             */
            kind: "flow";
            /**
             * Mode
             * @enum {string}
             */
            mode: "snapshot" | "due_in_period";
            /** Row Keys */
            row_keys: string[];
            /** Rules */
            rules: components["schemas"]["RuleOut"][];
            /** Stage Key */
            stage_key: string;
            /** Stage Label */
            stage_label: string;
        };
        /**
         * Freshness
         * @description Which contract run the answer is built from, and how old it is on the demo clock (F09-FR-07).
         */
        Freshness: {
            /** Contract Run Id */
            contract_run_id: string | null;
            /** Freshness Minutes */
            freshness_minutes: number | null;
            /** Last Success At */
            last_success_at: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MetricExplain */
        MetricExplain: {
            /** Completed */
            completed: number | null;
            freshness: components["schemas"]["Freshness"];
            /**
             * Kind
             * @default metric
             * @constant
             */
            kind: "metric";
            /** Label */
            label: string;
            /** Metric Id */
            metric_id: string;
            /** Null Reason */
            null_reason: string | null;
            /** On Time */
            on_time: number | null;
            /** Pct */
            pct: string | null;
            /** Rows */
            rows: components["schemas"]["MetricRowOut"][];
            /** Sla Days */
            sla_days: number | null;
            /** Status */
            status: string;
            /** Week Start */
            week_start: string | null;
        };
        /** MetricOut */
        MetricOut: {
            /** Computed In */
            computed_in: string;
            /** Label */
            label: string;
            /** Metric Id */
            metric_id: string;
            /** Null Reason */
            null_reason: string | null;
            /** Sla Days */
            sla_days: number | null;
            /** Stage Key */
            stage_key: string | null;
            /** Status */
            status: string;
            /** Weeks */
            weeks: components["schemas"]["WeekOut"][];
        };
        /** MetricRowOut */
        MetricRowOut: {
            /** Duration Days */
            duration_days: number | null;
            /** Entry Date */
            entry_date: string | null;
            /** Exit Date */
            exit_date: string | null;
            /** On Time */
            on_time: boolean | null;
            /** Row Key */
            row_key: string;
            /** Sla Days */
            sla_days: number | null;
        };
        /** MetricsOut */
        MetricsOut: {
            /** Filtered */
            filtered: boolean;
            freshness: components["schemas"]["Freshness"];
            /** Metrics */
            metrics: components["schemas"]["MetricOut"][];
            /** Week Starts */
            week_starts: string[];
        };
        /** NeedByIn */
        NeedByIn: {
            /** Adjusted Date */
            adjusted_date?: string | null;
            /**
             * Expedite
             * @default false
             */
            expedite: boolean;
            /** Note */
            note?: string | null;
            /** Reason Code */
            reason_code?: string | null;
        };
        /** OverrideOut */
        OverrideOut: {
            /** Author User Key */
            author_user_key: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Field */
            field: string;
            /** Id */
            id: number;
            /** Is Current */
            is_current: boolean;
            /** Note */
            note: string | null;
            /** Reason Code */
            reason_code: string | null;
            /** Value */
            value: unknown;
            /** Version */
            version: number;
        };
        /** OverviewOut */
        OverviewOut: {
            /** Alerts */
            alerts: components["schemas"]["AlertOut"][];
            /** Flow Strip */
            flow_strip: components["schemas"]["FlowEntry"][];
            freshness: components["schemas"]["Freshness"];
            /**
             * Mode
             * @enum {string}
             */
            mode: "snapshot" | "due_in_period";
            /** On Hold Count */
            on_hold_count: number;
            /** Rows */
            rows: components["schemas"]["RowOut"][];
            /** Total */
            total: number;
        };
        /** PipelineStatusOut */
        PipelineStatusOut: {
            /** Last Run Id */
            last_run_id: string;
            /**
             * Last Success At
             * Format: date-time
             */
            last_success_at: string;
            /** Row Count */
            row_count: number;
            /** Source Freshness */
            source_freshness: {
                [key: string]: unknown;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** PlanOut */
        PlanOut: {
            /** Compressed */
            compressed: boolean;
            /** Compression Ratio */
            compression_ratio: string | null;
            /** Days In Stage */
            days_in_stage: number | null;
            /** Days Remaining */
            days_remaining: number | null;
            /** Effective Slas */
            effective_slas: {
                [key: string]: number;
            };
            /** Expected Completion */
            expected_completion: string | null;
            /** Late */
            late: boolean;
            /** Late Reason Auto */
            late_reason_auto: string | null;
            /** Must Complete By */
            must_complete_by: {
                [key: string]: string;
            };
            /** Rag */
            rag: string | null;
        };
        /** ReferenceOut */
        ReferenceOut: {
            /** Campaigns */
            campaigns: string[];
            /** Classes */
            classes: string[];
            /** Flags */
            flags: string[];
            /** Metric Rag */
            metric_rag: {
                [key: string]: number;
            };
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            }[];
            /** Molecule Types */
            molecule_types: string[];
            /** Periods */
            periods: string[];
            /** Reason Codes */
            reason_codes: {
                [key: string]: unknown;
            }[];
            /** Site Name */
            site_name: string;
            /** Site Timezone */
            site_timezone: string;
            /** Stages */
            stages: {
                [key: string]: unknown;
            }[];
        };
        /**
         * RowDetail
         * @description ``GET /api/rows/{row_key}``: the row with every mirror column, its overrides, comments and siblings.
         */
        RowDetail: {
            /** Adjusted Need By Date */
            adjusted_need_by_date: string | null;
            /** Adjusted Reason Code */
            adjusted_reason_code: string | null;
            /** Air Gap */
            air_gap: boolean;
            /** Air Gap Hours */
            air_gap_hours: number;
            /** Batch No */
            batch_no: string;
            /** Campaign */
            campaign: string | null;
            /** Comment Count */
            comment_count: number;
            /** Comments */
            comments: components["schemas"]["CommentOut"][];
            /** Current Overrides */
            current_overrides: {
                [key: string]: components["schemas"]["OverrideOut"];
            };
            /** Current Stage Entry Date */
            current_stage_entry_date: string | null;
            /** Days In Stage */
            days_in_stage: number | null;
            /** Deviation Light */
            deviation_light: string | null;
            /** Deviations */
            deviations: components["schemas"]["DeviationOut"][];
            /** Expedite */
            expedite: boolean;
            /** Facts */
            facts: {
                [key: string]: unknown;
            };
            flags: components["schemas"]["FlagsOut"];
            freshness: components["schemas"]["Freshness"];
            /** Inbound Light */
            inbound_light: string | null;
            /** Inspection Lot No */
            inspection_lot_no: string;
            /** Late */
            late: boolean;
            /** Lims Status */
            lims_status: string | null;
            /** Lot Type */
            lot_type: string;
            /** Manual Status */
            manual_status: {
                [key: string]: unknown;
            } | null;
            /** Material Class */
            material_class: string | null;
            /** Material Desc */
            material_desc: string | null;
            /** Material No */
            material_no: string;
            /** Molecule Type */
            molecule_type: string | null;
            /** Operative Need By */
            operative_need_by: string | null;
            /** Override History */
            override_history: components["schemas"]["OverrideOut"][];
            plan: components["schemas"]["PlanOut"];
            /** Row Key */
            row_key: string;
            /** Siblings */
            siblings: components["schemas"]["RowOut"][];
            /** Stage Key */
            stage_key: string;
            /** Stage Label */
            stage_label: string;
            /** Stage Rule Id */
            stage_rule_id: string | null;
            /** Supplier Name */
            supplier_name: string | null;
            /** System Need By Locked */
            system_need_by_locked: string | null;
            /** Ud Code */
            ud_code: string | null;
        };
        /**
         * RowOut
         * @description One lot: the facts the table shows, the human input and the plan computed from both.
         */
        RowOut: {
            /** Adjusted Need By Date */
            adjusted_need_by_date: string | null;
            /** Adjusted Reason Code */
            adjusted_reason_code: string | null;
            /** Air Gap */
            air_gap: boolean;
            /** Air Gap Hours */
            air_gap_hours: number;
            /** Batch No */
            batch_no: string;
            /** Campaign */
            campaign: string | null;
            /** Comment Count */
            comment_count: number;
            /** Current Stage Entry Date */
            current_stage_entry_date: string | null;
            /** Days In Stage */
            days_in_stage: number | null;
            /** Deviation Light */
            deviation_light: string | null;
            /** Expedite */
            expedite: boolean;
            flags: components["schemas"]["FlagsOut"];
            /** Inbound Light */
            inbound_light: string | null;
            /** Inspection Lot No */
            inspection_lot_no: string;
            /** Late */
            late: boolean;
            /** Lims Status */
            lims_status: string | null;
            /** Lot Type */
            lot_type: string;
            /** Manual Status */
            manual_status: {
                [key: string]: unknown;
            } | null;
            /** Material Class */
            material_class: string | null;
            /** Material Desc */
            material_desc: string | null;
            /** Material No */
            material_no: string;
            /** Molecule Type */
            molecule_type: string | null;
            /** Operative Need By */
            operative_need_by: string | null;
            plan: components["schemas"]["PlanOut"];
            /** Row Key */
            row_key: string;
            /** Stage Key */
            stage_key: string;
            /** Stage Label */
            stage_label: string;
            /** Stage Rule Id */
            stage_rule_id: string | null;
            /** Supplier Name */
            supplier_name: string | null;
            /** System Need By Locked */
            system_need_by_locked: string | null;
            /** Ud Code */
            ud_code: string | null;
        };
        /** RuleOut */
        RuleOut: {
            /** Condition Sql */
            condition_sql: string;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Inputs */
            inputs: string[];
            /** Stage Key */
            stage_key: string;
        };
        /** StageExplain */
        StageExplain: {
            freshness: components["schemas"]["Freshness"];
            /** Input Values */
            input_values: {
                [key: string]: unknown;
            };
            /**
             * Kind
             * @default stage
             * @constant
             */
            kind: "stage";
            /** Row Key */
            row_key: string;
            rule: components["schemas"]["RuleOut"];
            /** Source Refs */
            source_refs: unknown;
            /** Stage Key */
            stage_key: string;
            /** Stage Label */
            stage_label: string;
        };
        /** StatusIn */
        StatusIn: {
            /** Rag */
            rag?: ("red" | "amber" | "green") | null;
            /** Reason */
            reason?: string | null;
            /** Team */
            team?: string | null;
        };
        /** SyncEventOut */
        SyncEventOut: {
            /** Age Seconds */
            age_seconds: number;
            /** Claimed At */
            claimed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Rows Upserted */
            rows_upserted: number | null;
            /** Run Id */
            run_id: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
        };
        /** SyncStatusOut */
        SyncStatusOut: {
            /** Events */
            events: components["schemas"]["SyncEventOut"][];
            /** Freshness Minutes */
            freshness_minutes: number | null;
            pipeline_status: components["schemas"]["PipelineStatusOut"] | null;
            /** Watermarks */
            watermarks: components["schemas"]["WatermarkOut"][];
        };
        /** UserOut */
        UserOut: {
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** User Key */
            user_key: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatermarkOut */
        WatermarkOut: {
            /** Age Seconds */
            age_seconds: number;
            /** Object Name */
            object_name: string;
            /** Run Id */
            run_id: string;
            /**
             * Synced At
             * Format: date-time
             */
            synced_at: string;
        };
        /** WeekOut */
        WeekOut: {
            /** Completed */
            completed: number;
            /** On Time */
            on_time: number;
            /** Pct */
            pct: string | null;
            /** Rag */
            rag: string | null;
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_api_audit_get: {
        parameters: {
            query?: {
                row_key?: string | null;
                actor?: string | null;
                action?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-demo-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_clock_api_clock_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClockOut"];
                };
            };
        };
    };
    explain_figure_api_explain_get: {
        parameters: {
            query: {
                field: string;
                week?: string | null;
                "type[]"?: string[] | null;
                "class[]"?: string[] | null;
                "campaign[]"?: string[] | null;
                "flags[]"?: string[] | null;
                stage?: string | null;
                period?: string;
                from?: string | null;
                to?: string | null;
                q?: string | null;
            };
            header?: {
                "x-demo-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricExplain"] | components["schemas"]["FlowExplain"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_api_export_csv_get: {
        parameters: {
            query?: {
                "type[]"?: string[] | null;
                "class[]"?: string[] | null;
                "campaign[]"?: string[] | null;
                "flags[]"?: string[] | null;
                stage?: string | null;
                period?: string;
                from?: string | null;
                to?: string | null;
                q?: string | null;
            };
            header?: {
                "x-demo-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: {
                "type[]"?: string[] | null;
                "class[]"?: string[] | null;
                "campaign[]"?: string[] | null;
                "flags[]"?: string[] | null;
                stage?: string | null;
                period?: string;
                from?: string | null;
                to?: string | null;
                q?: string | null;
            };
            header?: {
                "x-demo-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reference_api_reference_get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_row_api_rows__row_key__get: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-user"?: string | null;
            };
            path: {
                row_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_comment_api_rows__row_key__comments_post: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-user"?: string | null;
            };
            path: {
                row_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_row_api_rows__row_key__explain_get: {
        parameters: {
            query: {
                field: string;
            };
            header?: {
                "x-demo-user"?: string | null;
            };
            path: {
                row_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageExplain"] | components["schemas"]["CompletionExplain"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_need_by_api_rows__row_key__need_by_put: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-user"?: string | null;
            };
            path: {
                row_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NeedByIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_status_api_rows__row_key__status_put: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-user"?: string | null;
            };
            path: {
                row_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_status_api_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusOut"];
                };
            };
        };
    };
    trigger_api_sync_trigger_post: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    webhook_api_sync_webhook_post: {
        parameters: {
            query?: never;
            header?: {
                "x-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
}
