"""initial erp schema

Revision ID: 0001
Revises:
Create Date: 2026-10-04 10:58:46.133760

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counter",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_counter_updated_at"), "counter", ["updated_at"], unique=False)
    op.create_table(
        "lfa1",
        sa.Column("lifnr", sa.Text(), nullable=False),
        sa.Column("name1", sa.Text(), nullable=False),
        sa.Column("land1", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("lifnr"),
    )
    op.create_index(op.f("ix_lfa1_updated_at"), "lfa1", ["updated_at"], unique=False)
    op.create_table(
        "mara",
        sa.Column("matnr", sa.Text(), nullable=False),
        sa.Column("maktx", sa.Text(), nullable=False),
        sa.Column("mtart", sa.Text(), nullable=False),
        sa.Column("zmolty", sa.Text(), nullable=False),
        sa.Column("zclass", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("matnr"),
    )
    op.create_index(op.f("ix_mara_updated_at"), "mara", ["updated_at"], unique=False)
    op.create_table(
        "t001l",
        sa.Column("lgort", sa.Text(), nullable=False),
        sa.Column("lgobe", sa.Text(), nullable=False),
        sa.Column("zloctype", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("zloctype in ('onsite', '3pl')", name="ck_t001l_zloctype"),
        sa.PrimaryKeyConstraint("lgort"),
    )
    op.create_index(op.f("ix_t001l_updated_at"), "t001l", ["updated_at"], unique=False)
    op.create_table(
        "mcha",
        sa.Column("matnr", sa.Text(), nullable=False),
        sa.Column("charg", sa.Text(), nullable=False),
        sa.Column("lifnr", sa.Text(), nullable=False),
        sa.Column("licha", sa.Text(), nullable=False),
        sa.Column("hsdat", sa.Date(), nullable=True),
        sa.Column("vfdat", sa.Date(), nullable=True),
        sa.Column("zstat", sa.Text(), server_default="", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("zstat in ('', 'H')", name="ck_mcha_zstat"),
        sa.ForeignKeyConstraint(
            ["lifnr"],
            ["lfa1.lifnr"],
        ),
        sa.ForeignKeyConstraint(
            ["matnr"],
            ["mara.matnr"],
        ),
        sa.PrimaryKeyConstraint("matnr", "charg"),
    )
    op.create_index(op.f("ix_mcha_updated_at"), "mcha", ["updated_at"], unique=False)
    op.create_table(
        "mdez",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("matnr", sa.Text(), nullable=False),
        sa.Column("campaign", sa.Text(), nullable=False),
        sa.Column("bdter", sa.Date(), nullable=False),
        sa.Column("bdmng", sa.Numeric(precision=13, scale=3), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["matnr"],
            ["mara.matnr"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_mdez_matnr", "mdez", ["matnr"], unique=False)
    op.create_index(op.f("ix_mdez_updated_at"), "mdez", ["updated_at"], unique=False)
    op.create_table(
        "mchb",
        sa.Column("matnr", sa.Text(), nullable=False),
        sa.Column("charg", sa.Text(), nullable=False),
        sa.Column("lgort", sa.Text(), nullable=False),
        sa.Column("insme", sa.Numeric(precision=13, scale=3), nullable=False),
        sa.Column("speme", sa.Numeric(precision=13, scale=3), nullable=False),
        sa.Column("clabs", sa.Numeric(precision=13, scale=3), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("insme >= 0 and speme >= 0 and clabs >= 0", name="ck_mchb_non_negative"),
        sa.ForeignKeyConstraint(
            ["lgort"],
            ["t001l.lgort"],
        ),
        sa.ForeignKeyConstraint(
            ["matnr", "charg"],
            ["mcha.matnr", "mcha.charg"],
        ),
        sa.PrimaryKeyConstraint("matnr", "charg", "lgort"),
    )
    op.create_index(op.f("ix_mchb_updated_at"), "mchb", ["updated_at"], unique=False)
    op.create_table(
        "mseg",
        sa.Column("mblnr", sa.Text(), nullable=False),
        sa.Column("zeile", sa.Text(), nullable=False),
        sa.Column("bwart", sa.Text(), nullable=False),
        sa.Column("matnr", sa.Text(), nullable=False),
        sa.Column("charg", sa.Text(), nullable=False),
        sa.Column("lgort", sa.Text(), nullable=False),
        sa.Column("umlgo", sa.Text(), nullable=True),
        sa.Column("budat", sa.Date(), nullable=False),
        sa.Column("menge", sa.Numeric(precision=13, scale=3), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("bwart in ('101', '102', '311')", name="ck_mseg_bwart"),
        sa.CheckConstraint("menge > 0", name="ck_mseg_menge"),
        sa.ForeignKeyConstraint(
            ["lgort"],
            ["t001l.lgort"],
        ),
        sa.ForeignKeyConstraint(
            ["matnr", "charg"],
            ["mcha.matnr", "mcha.charg"],
        ),
        sa.ForeignKeyConstraint(
            ["umlgo"],
            ["t001l.lgort"],
        ),
        sa.PrimaryKeyConstraint("mblnr", "zeile"),
    )
    op.create_index("ix_mseg_matnr_charg", "mseg", ["matnr", "charg"], unique=False)
    op.create_index(op.f("ix_mseg_updated_at"), "mseg", ["updated_at"], unique=False)
    op.create_table(
        "qals",
        sa.Column("prueflos", sa.Text(), nullable=False),
        sa.Column("art", sa.Text(), nullable=False),
        sa.Column("matnr", sa.Text(), nullable=False),
        sa.Column("charg", sa.Text(), nullable=False),
        sa.Column("pastrterm", sa.Date(), nullable=False),
        sa.Column("vcode", sa.String(), nullable=True),
        sa.Column("vdatum", sa.Date(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("art in ('01', '09')", name="ck_qals_art"),
        sa.ForeignKeyConstraint(
            ["matnr", "charg"],
            ["mcha.matnr", "mcha.charg"],
        ),
        sa.PrimaryKeyConstraint("prueflos"),
    )
    op.create_index("ix_qals_matnr_charg", "qals", ["matnr", "charg"], unique=False)
    op.create_index(op.f("ix_qals_updated_at"), "qals", ["updated_at"], unique=False)
    op.create_table(
        "zinbchk",
        sa.Column("prueflos", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("completed_on", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status in ('open', 'passed', 'failed')", name="ck_zinbchk_status"),
        sa.ForeignKeyConstraint(
            ["prueflos"],
            ["qals.prueflos"],
        ),
        sa.PrimaryKeyConstraint("prueflos"),
    )
    op.create_index(op.f("ix_zinbchk_updated_at"), "zinbchk", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_zinbchk_updated_at"), table_name="zinbchk")
    op.drop_table("zinbchk")
    op.drop_index(op.f("ix_qals_updated_at"), table_name="qals")
    op.drop_index("ix_qals_matnr_charg", table_name="qals")
    op.drop_table("qals")
    op.drop_index(op.f("ix_mseg_updated_at"), table_name="mseg")
    op.drop_index("ix_mseg_matnr_charg", table_name="mseg")
    op.drop_table("mseg")
    op.drop_index(op.f("ix_mchb_updated_at"), table_name="mchb")
    op.drop_table("mchb")
    op.drop_index(op.f("ix_mdez_updated_at"), table_name="mdez")
    op.drop_index("ix_mdez_matnr", table_name="mdez")
    op.drop_table("mdez")
    op.drop_index(op.f("ix_mcha_updated_at"), table_name="mcha")
    op.drop_table("mcha")
    op.drop_index(op.f("ix_t001l_updated_at"), table_name="t001l")
    op.drop_table("t001l")
    op.drop_index(op.f("ix_mara_updated_at"), table_name="mara")
    op.drop_table("mara")
    op.drop_index(op.f("ix_lfa1_updated_at"), table_name="lfa1")
    op.drop_table("lfa1")
    op.drop_index(op.f("ix_counter_updated_at"), table_name="counter")
    op.drop_table("counter")
    # ### end Alembic commands ###
