"""``GET /api/schema``: the published contract, as the Schema Reference page lists it (F21-FR-06).

The file is generated by ``tools/contract_schema.py`` (``make contract-json``) and copied into the image; the
API only serves it. ``CONTRACT_JSON`` overrides the location.
"""

import json
import os
from functools import lru_cache
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from app_api.auth import current_user

router = APIRouter(dependencies=[Depends(current_user)])

_IMAGE_PATH = Path("/app/specs/contract.json")


class ColumnOut(BaseModel):
    name: str
    type: str
    description: str


class ObjectOut(BaseModel):
    name: str
    description: str
    grain: str
    columns: list[ColumnOut]


class SchemaOut(BaseModel):
    objects: list[ObjectOut]


def contract_path() -> Path:
    """The env override, else the repository copy (a checkout), else the one in the image."""
    override = os.environ.get("CONTRACT_JSON")
    if override:
        return Path(override)
    checkout = Path(__file__).resolve().parents[5] / "specs" / "contract.json"
    return checkout if checkout.is_file() else _IMAGE_PATH


@lru_cache(maxsize=4)
def _load(path: str) -> SchemaOut:
    return SchemaOut.model_validate(json.loads(Path(path).read_text(encoding="utf-8")))


@router.get("/schema")
def schema() -> SchemaOut:
    path = contract_path()
    if not path.is_file():
        raise HTTPException(
            status_code=503, detail=f"the contract file {path} is missing; run make contract-json"
        )
    return _load(str(path))
