"""demo clock

Revision ID: 0001
Revises:
Create Date: 2026-10-04 11:10:25.752646

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "demo_clock",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("now_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("frozen", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint("id = 1", name="ck_demo_clock_single_row"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("demo_clock")
    # ### end Alembic commands ###
