"""app schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-04 16:20:38.500186

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_trace",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("trace_id", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("step_type", sa.Text(), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "step_type IN ('input','tool_call','tool_result','model_request','model_response','validation','decision','action')",
            name="ck_agent_trace_step_type",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agent_trace_trace_seq", "agent_trace", ["trace_id", "seq"], unique=False)
    op.create_table(
        "app_user",
        sa.Column("user_key", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "role IN ('planner','qc_lead','qa_release','viewer','admin')", name="ck_app_user_role"
        ),
        sa.PrimaryKeyConstraint("user_key"),
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_key", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("row_key", sa.Text(), nullable=True),
        sa.Column("details_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_event_at"), "audit_event", ["at"], unique=False)
    op.create_index(op.f("ix_audit_event_row_key"), "audit_event", ["row_key"], unique=False)
    op.create_table(
        "mirror_batch_pipeline",
        sa.Column("row_key", sa.Text(), nullable=False),
        sa.Column("material_no", sa.Text(), nullable=True),
        sa.Column("material_desc", sa.Text(), nullable=True),
        sa.Column("material_class", sa.Text(), nullable=True),
        sa.Column("molecule_type", sa.Text(), nullable=True),
        sa.Column("supplier_id", sa.Text(), nullable=True),
        sa.Column("supplier_name", sa.Text(), nullable=True),
        sa.Column("supplier_batch", sa.Text(), nullable=True),
        sa.Column("batch_no", sa.Text(), nullable=True),
        sa.Column("batch_status_code", sa.Text(), nullable=True),
        sa.Column("inspection_lot_no", sa.Text(), nullable=True),
        sa.Column("lot_type", sa.Text(), nullable=True),
        sa.Column("lot_start_date", sa.Date(), nullable=True),
        sa.Column("storage_location", sa.Text(), nullable=True),
        sa.Column("location_type", sa.Text(), nullable=True),
        sa.Column("received_location_type", sa.Text(), nullable=True),
        sa.Column("stock_category", sa.Text(), nullable=True),
        sa.Column("gr_date", sa.Date(), nullable=True),
        sa.Column("transfer_to_site_date", sa.Date(), nullable=True),
        sa.Column("inbound_check_status", sa.Text(), nullable=True),
        sa.Column("inbound_check_completed_date", sa.Date(), nullable=True),
        sa.Column("sample_id", sa.Text(), nullable=True),
        sa.Column("sample_collected_date", sa.Date(), nullable=True),
        sa.Column("offsite_test", sa.Boolean(), nullable=True),
        sa.Column("external_lab", sa.Text(), nullable=True),
        sa.Column("sample_shipped_date", sa.Date(), nullable=True),
        sa.Column("lims_status", sa.Text(), nullable=True),
        sa.Column("lims_approved_date", sa.Date(), nullable=True),
        sa.Column("lims_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ud_code", sa.Text(), nullable=True),
        sa.Column("ud_date", sa.Date(), nullable=True),
        sa.Column("erp_results_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("campaign", sa.Text(), nullable=True),
        sa.Column("system_need_by_date", sa.Date(), nullable=True),
        sa.Column("open_deviation_count", sa.BigInteger(), nullable=True),
        sa.Column("closed_deviation_count", sa.BigInteger(), nullable=True),
        sa.Column("stage_key", sa.Text(), nullable=True),
        sa.Column("stage_rule_id", sa.Text(), nullable=True),
        sa.Column("stage_sort", sa.BigInteger(), nullable=True),
        sa.Column("current_stage_entry_date", sa.Date(), nullable=True),
        sa.Column("lims_rejected", sa.Boolean(), nullable=True),
        sa.Column("receipt_entry", sa.Date(), nullable=True),
        sa.Column("receipt_exit", sa.Date(), nullable=True),
        sa.Column("call_off_entry", sa.Date(), nullable=True),
        sa.Column("call_off_exit", sa.Date(), nullable=True),
        sa.Column("sampling_entry", sa.Date(), nullable=True),
        sa.Column("sampling_exit", sa.Date(), nullable=True),
        sa.Column("qc_ship_entry", sa.Date(), nullable=True),
        sa.Column("qc_ship_exit", sa.Date(), nullable=True),
        sa.Column("qc_testing_entry", sa.Date(), nullable=True),
        sa.Column("qc_testing_exit", sa.Date(), nullable=True),
        sa.Column("qa_release_entry", sa.Date(), nullable=True),
        sa.Column("qa_release_exit", sa.Date(), nullable=True),
        sa.Column("applicable_sla_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("system_need_by_locked", sa.Date(), nullable=True),
        sa.Column("on_hold", sa.Boolean(), nullable=True),
        sa.Column("erp_blocked", sa.Boolean(), nullable=True),
        sa.Column("re_eval", sa.Boolean(), nullable=True),
        sa.Column("offsite", sa.Boolean(), nullable=True),
        sa.Column("full_spec", sa.Boolean(), nullable=True),
        sa.Column("ud_rejected", sa.Boolean(), nullable=True),
        sa.Column("deviation_light", sa.Text(), nullable=True),
        sa.Column("inbound_light", sa.Text(), nullable=True),
        sa.Column("snapshot_date", sa.Date(), nullable=True),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contract_run_id", sa.Text(), nullable=False),
        sa.Column("mirrored_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("row_key"),
    )
    op.create_index(
        "ix_mirror_batch_pipeline_material_no_batch_no",
        "mirror_batch_pipeline",
        ["material_no", "batch_no"],
        unique=False,
    )
    op.create_index(
        "ix_mirror_batch_pipeline_stage_key", "mirror_batch_pipeline", ["stage_key"], unique=False
    )
    op.create_table(
        "mirror_deviations",
        sa.Column("deviation_no", sa.Text(), nullable=False),
        sa.Column("material_no", sa.Text(), nullable=False),
        sa.Column("batch_no", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("severity", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("opened_on", sa.Date(), nullable=True),
        sa.Column("closed_on", sa.Date(), nullable=True),
        sa.Column("root_cause_category", sa.Text(), nullable=True),
        sa.Column("owner", sa.Text(), nullable=True),
        sa.Column("contract_run_id", sa.Text(), nullable=False),
        sa.Column("mirrored_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("deviation_no", "material_no", "batch_no"),
    )
    op.create_index(
        "ix_mirror_deviations_material_no_batch_no",
        "mirror_deviations",
        ["material_no", "batch_no"],
        unique=False,
    )
    op.create_table(
        "mirror_metric_reference",
        sa.Column("metric_id", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("stage_key", sa.Text(), nullable=True),
        sa.Column("sla_days", sa.BigInteger(), nullable=True),
        sa.Column("computed_in", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("null_reason", sa.Text(), nullable=True),
        sa.Column("contract_run_id", sa.Text(), nullable=False),
        sa.Column("mirrored_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("metric_id"),
    )
    op.create_table(
        "mirror_pipeline_status",
        sa.Column("last_run_id", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("source_freshness_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("contract_run_id", sa.Text(), nullable=False),
        sa.Column("mirrored_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("last_run_id"),
    )
    op.create_table(
        "mirror_reason_codes",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("contract_run_id", sa.Text(), nullable=False),
        sa.Column("mirrored_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "mirror_stage_reference",
        sa.Column("stage_key", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("sort", sa.BigInteger(), nullable=True),
        sa.Column("sla_days", sa.BigInteger(), nullable=True),
        sa.Column("reeval_sla_days", sa.BigInteger(), nullable=True),
        sa.Column("team", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("terminal", sa.Boolean(), nullable=True),
        sa.Column("contract_run_id", sa.Text(), nullable=False),
        sa.Column("mirrored_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("stage_key"),
    )
    op.create_table(
        "mirror_weekly_metric_rows",
        sa.Column("metric_id", sa.Text(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("row_key", sa.Text(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("exit_date", sa.Date(), nullable=True),
        sa.Column("duration_days", sa.BigInteger(), nullable=True),
        sa.Column("sla_days", sa.BigInteger(), nullable=True),
        sa.Column("on_time", sa.Boolean(), nullable=True),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.Column("contract_run_id", sa.Text(), nullable=False),
        sa.Column("mirrored_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("metric_id", "week_start", "row_key"),
    )
    op.create_index(
        "ix_mirror_weekly_metric_rows_row_key", "mirror_weekly_metric_rows", ["row_key"], unique=False
    )
    op.create_table(
        "mirror_weekly_metrics",
        sa.Column("metric_id", sa.Text(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("completed", sa.BigInteger(), nullable=True),
        sa.Column("on_time", sa.BigInteger(), nullable=True),
        sa.Column("pct", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.Column("contract_run_id", sa.Text(), nullable=False),
        sa.Column("mirrored_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("metric_id", "week_start"),
    )
    op.create_table(
        "proposal",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("agent_key", sa.Text(), nullable=False),
        sa.Column("row_key", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validator_result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("required_role", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_by", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending_approval','rejected_by_validator','approved','rejected','executed')",
            name="ck_proposal_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proposal_trace_id"), "proposal", ["trace_id"], unique=False)
    op.create_table(
        "sync_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("rows_upserted", sa.Integer(), nullable=True),
        sa.CheckConstraint("source IN ('webhook','poll','manual')", name="ck_sync_event_source"),
        sa.CheckConstraint("status IN ('pending','claimed','done','failed')", name="ck_sync_event_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sync_event_status_received", "sync_event", ["status", "received_at"], unique=False)
    op.create_table(
        "watermark",
        sa.Column("object_name", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("object_name"),
    )
    op.create_table(
        "action_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("proposal_id", sa.BigInteger(), nullable=False),
        sa.Column("action_type", sa.Text(), nullable=False),
        sa.Column("rendered_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("row_key", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author_user_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_key"],
            ["app_user.user_key"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comment_row_key"), "comment", ["row_key"], unique=False)
    op.create_table(
        "override_value",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("row_key", sa.Text(), nullable=False),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason_code", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("author_user_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "field IN ('adjusted_need_by_date','expedite','manual_status','delivery_date','delivery_location')",
            name="ck_override_value_field",
        ),
        sa.ForeignKeyConstraint(
            ["author_user_key"],
            ["app_user.user_key"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_override_value_current",
        "override_value",
        ["row_key", "field"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )

    # The five demo users (04-data-contracts section 5), seeded here so they survive any restart.
    users = sa.table("app_user", sa.column("user_key"), sa.column("display_name"), sa.column("role"))
    op.bulk_insert(
        users,
        [
            {"user_key": "pat", "display_name": "Pat", "role": "planner"},
            {"user_key": "quinn", "display_name": "Quinn", "role": "qc_lead"},
            {"user_key": "alex", "display_name": "Alex", "role": "qa_release"},
            {"user_key": "sam", "display_name": "Sam", "role": "viewer"},
            {"user_key": "admin", "display_name": "Admin", "role": "admin"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_override_value_current", table_name="override_value", postgresql_where=sa.text("is_current")
    )
    op.drop_table("override_value")
    op.drop_index(op.f("ix_comment_row_key"), table_name="comment")
    op.drop_table("comment")
    op.drop_table("action_log")
    op.drop_table("watermark")
    op.drop_index("ix_sync_event_status_received", table_name="sync_event")
    op.drop_table("sync_event")
    op.drop_index(op.f("ix_proposal_trace_id"), table_name="proposal")
    op.drop_table("proposal")
    op.drop_table("mirror_weekly_metrics")
    op.drop_index("ix_mirror_weekly_metric_rows_row_key", table_name="mirror_weekly_metric_rows")
    op.drop_table("mirror_weekly_metric_rows")
    op.drop_table("mirror_stage_reference")
    op.drop_table("mirror_reason_codes")
    op.drop_table("mirror_pipeline_status")
    op.drop_table("mirror_metric_reference")
    op.drop_index("ix_mirror_deviations_material_no_batch_no", table_name="mirror_deviations")
    op.drop_table("mirror_deviations")
    op.drop_index("ix_mirror_batch_pipeline_stage_key", table_name="mirror_batch_pipeline")
    op.drop_index("ix_mirror_batch_pipeline_material_no_batch_no", table_name="mirror_batch_pipeline")
    op.drop_table("mirror_batch_pipeline")
    op.drop_index(op.f("ix_audit_event_row_key"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_at"), table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_table("app_user")
    op.drop_index("ix_agent_trace_trace_seq", table_name="agent_trace")
    op.drop_table("agent_trace")
    # ### end Alembic commands ###
